### ISSUE TITLE
$.fn.enable and $.fn.disable conflict with methods i define

### ISSUE THREAD

**Issue by Only-Bimal** [zingchart/ZingChart-jQuery#5]
In my code i have defined functions "$.fn.enable" and "$.fn.disable" to enable and disable controls in the DOM. The two methods defined in the library conflict and overwrite my definitions. 
As the methods defined in the library are for Zingchart only, shouldn't they have some other name or may be in a different namespace.

Currently, I've to disable/rename the methods to keep the binding intact.

**Comment by gnardecky** [comment]
I have updated the following methods:

`enable -> enableChart`

`disabled -> disabledChart`
